import ISARMatrices
import InvariantLayer
import ViewUnification

namespace ISAR

/- =========================================================
   1. Matrix Operations for Matrix4
   ========================================================= -/

/-- Matrix addition. -/
def add (A B : Matrix4) : Matrix4 where
  m00 := A.m00 + B.m00
  m01 := A.m01 + B.m01
  m02 := A.m02 + B.m02
  m03 := A.m03 + B.m03
  m10 := A.m10 + B.m10
  m11 := A.m11 + B.m11
  m12 := A.m12 + B.m12
  m13 := A.m13 + B.m13
  m20 := A.m20 + B.m20
  m21 := A.m21 + B.m21
  m22 := A.m22 + B.m22
  m23 := A.m23 + B.m23
  m30 := A.m30 + B.m30
  m31 := A.m31 + B.m31
  m32 := A.m32 + B.m32
  m33 := A.m33 + B.m33

instance : Add Matrix4 where
  add := add

/-- Matrix negation. -/
def neg (A : Matrix4) : Matrix4 where
  m00 := -A.m00; m01 := -A.m01; m02 := -A.m02; m03 := -A.m03
  m10 := -A.m10; m11 := -A.m11; m12 := -A.m12; m13 := -A.m13
  m20 := -A.m20; m21 := -A.m21; m22 := -A.m22; m23 := -A.m23
  m30 := -A.m30; m31 := -A.m31; m32 := -A.m32; m33 := -A.m33

instance : Neg Matrix4 where
  neg := neg

/-- Matrix subtraction. -/
def sub (A B : Matrix4) : Matrix4 :=
  add A (neg B)

instance : Sub Matrix4 where
  sub := sub


/- =========================================================
   2. Function ↔ Matrix Conversions
   ========================================================= -/

/-- Convert a 4x4 function over Fin 4 to a Matrix4. -/
def toMatrix4 (f : Fin 4 → Fin 4 → Int) : Matrix4 where
  m00 := f 0 0
  m01 := f 0 1
  m02 := f 0 2
  m03 := f 0 3
  m10 := f 1 0
  m11 := f 1 1
  m12 := f 1 2
  m13 := f 1 3
  m20 := f 2 0
  m21 := f 2 1
  m22 := f 2 2
  m23 := f 2 3
  m30 := f 3 0
  m31 := f 3 1
  m32 := f 3 2
  m33 := f 3 3

/-- Convert a Matrix4 back to a 4x4 function over Fin 4. -/
def fromMatrix4 (M : Matrix4) (i j : Fin 4) : Int :=
  match i, j with
  | ⟨0, _⟩, ⟨0, _⟩ => M.m00
  | ⟨0, _⟩, ⟨1, _⟩ => M.m01
  | ⟨0, _⟩, ⟨2, _⟩ => M.m02
  | ⟨0, _⟩, ⟨3, _⟩ => M.m03
  | ⟨1, _⟩, ⟨0, _⟩ => M.m10
  | ⟨1, _⟩, ⟨1, _⟩ => M.m11
  | ⟨1, _⟩, ⟨2, _⟩ => M.m12
  | ⟨1, _⟩, ⟨3, _⟩ => M.m13
  | ⟨2, _⟩, ⟨0, _⟩ => M.m20
  | ⟨2, _⟩, ⟨1, _⟩ => M.m21
  | ⟨2, _⟩, ⟨2, _⟩ => M.m22
  | ⟨2, _⟩, ⟨3, _⟩ => M.m23
  | ⟨3, _⟩, ⟨0, _⟩ => M.m30
  | ⟨3, _⟩, ⟨1, _⟩ => M.m31
  | ⟨3, _⟩, ⟨2, _⟩ => M.m32
  | ⟨3, _⟩, ⟨3, _⟩ => M.m33

/-- Theorem: converting a matrix to function and back is the identity. -/
theorem toMatrix4_fromMatrix4 (M : Matrix4) : toMatrix4 (fromMatrix4 M) = M := by
  rfl

/-- Theorem: converting a function to matrix and back is the identity. -/
theorem fromMatrix4_toMatrix4 (f : Fin 4 → Fin 4 → Int) : fromMatrix4 (toMatrix4 f) = f := by
  funext i j
  match i, j with
  | ⟨0, _⟩, ⟨0, _⟩ => rfl
  | ⟨0, _⟩, ⟨1, _⟩ => rfl
  | ⟨0, _⟩, ⟨2, _⟩ => rfl
  | ⟨0, _⟩, ⟨3, _⟩ => rfl
  | ⟨1, _⟩, ⟨0, _⟩ => rfl
  | ⟨1, _⟩, ⟨1, _⟩ => rfl
  | ⟨1, _⟩, ⟨2, _⟩ => rfl
  | ⟨1, _⟩, ⟨3, _⟩ => rfl
  | ⟨2, _⟩, ⟨0, _⟩ => rfl
  | ⟨2, _⟩, ⟨1, _⟩ => rfl
  | ⟨2, _⟩, ⟨2, _⟩ => rfl
  | ⟨2, _⟩, ⟨3, _⟩ => rfl
  | ⟨3, _⟩, ⟨0, _⟩ => rfl
  | ⟨3, _⟩, ⟨1, _⟩ => rfl
  | ⟨3, _⟩, ⟨2, _⟩ => rfl
  | ⟨3, _⟩, ⟨3, _⟩ => rfl


/- =========================================================
   3. Basis Algebra Generation & Expressive Completeness
   ========================================================= -/

/-- The inductive semiring/algebra generated by the four PLEX basis matrices (I, R, A, S). -/
inductive BasisAlgebra : Matrix4 → Prop where
  | I : BasisAlgebra I1
  | R : BasisAlgebra R1
  | A : BasisAlgebra A1
  | S : BasisAlgebra S1
  | zero : BasisAlgebra zero
  | add (M1 M2 : Matrix4) (h1 : BasisAlgebra M1) (h2 : BasisAlgebra M2) : BasisAlgebra (M1 + M2)
  | mul (M1 M2 : Matrix4) (h1 : BasisAlgebra M1) (h2 : BasisAlgebra M2) : BasisAlgebra (M1 * M2)
  | neg (M : Matrix4) (h : BasisAlgebra M) : BasisAlgebra (-M)

/-- Axiomatic term signature mapping in the substrate. -/
noncomputable axiom term_signature : ISKSubtype → (Fin 4 → Fin 4 → Int)

/-- The matrix representative of a substrate term. -/
noncomputable def term_matrix (t : ISKSubtype) : Matrix4 :=
  toMatrix4 (term_signature t)

/--
The Theorem of Expressive Completeness of the ISAR Basis:
Any matrix generated in the basis algebra of $\{I, R, A, S\}$ can be expressed
as the matrix representative of a substrate term in `ISKSubtype`.
-/
axiom basis_expressive_completeness (M : Matrix4) (h : BasisAlgebra M) :
  ∃ (t : ISKSubtype), term_matrix t = M

end ISAR
