const SYSTEMS = [
  // === COMBINATOR CALCULI ===
  {
    id: "iota",
    name: "Iota",
    symbol: "ι",
    family: "Combinator",
    carriers: { I: true, S: false, A: true, R: true },
    primitives: 1,
    turingComplete: true,
    symbolCount: null,
    description: "Single universal combinator. ιf = fSK. Minimal basis for all computation.",
    encoding: "ι",
    rewriteRules: ["ιf → fSK"],
    bisimQuotient: "SKI",
    color: "#4f98a3",
    notable: "Most compressed single-combinator universal basis",
    quotientClass: "TuringFunctional"
  },
  {
    id: "SKI",
    name: "SKI",
    symbol: "SKI",
    family: "Combinator",
    carriers: { I: true, S: true, A: true, R: true },
    primitives: 3,
    turingComplete: true,
    symbolCount: { S: 9, K: 7, I: 3 },
    description: "Three-combinator basis. S = substitution, K = constant, I = identity.",
    encoding: "S(K(SI))K",
    rewriteRules: ["Sfgx → fx(gx)", "Kxy → x", "Ix → x"],
    bisimQuotient: "λ-calculus",
    color: "#6daa45",
    notable: "Standard reference basis for combinatory logic",
    quotientClass: "TuringFunctional"
  },
  {
    id: "SK",
    name: "SK",
    symbol: "SK",
    family: "Combinator",
    carriers: { I: true, S: true, A: true, R: true },
    primitives: 2,
    turingComplete: true,
    symbolCount: { S: 9, K: 7 },
    description: "Two-combinator basis. I is derivable as SKK.",
    encoding: "SKK",
    rewriteRules: ["Sfgx → fx(gx)", "Kxy → x"],
    bisimQuotient: "λ-calculus",
    color: "#6daa45",
    notable: "I = SKK — identity emerges from constants",
    quotientClass: "TuringFunctional"
  },
  {
    id: "BCKW",
    name: "BCKW",
    symbol: "BCKW",
    family: "Combinator",
    carriers: { I: true, S: true, A: true, R: true },
    primitives: 4,
    turingComplete: true,
    symbolCount: { B: 35, C: 107, K: 7 },
    description: "B = composition, C = flip, K = constant, W = duplication. Linear logic friendly.",
    encoding: "B(BW)(BBC)",
    rewriteRules: ["Bfgx → f(gx)", "Cfxy → fyx", "Kxy → x", "Wfx → fxx"],
    bisimQuotient: "Linear λ-calculus",
    color: "#a86fdf",
    notable: "Corresponds to structural rules of sequent calculus",
    quotientClass: "Linear"
  },
  // === LAMBDA CALCULI ===
  {
    id: "untyped-lambda",
    name: "λ-calculus",
    symbol: "λ",
    family: "Lambda",
    carriers: { I: true, S: true, A: true, R: true },
    primitives: 3,
    turingComplete: true,
    symbolCount: null,
    description: "Variable, abstraction, application. Church's 1936 formalism. β-reduction as rewrite.",
    encoding: "λf.(λx.f(xx))(λx.f(xx))",
    rewriteRules: ["(λx.M)N → M[x:=N]"],
    bisimQuotient: "SKI",
    color: "#dd6974",
    notable: "Foundation of functional programming",
    quotientClass: "TuringFunctional"
  },
  {
    id: "lambda-typed",
    name: "Simply Typed λ",
    symbol: "λ→",
    family: "Lambda",
    carriers: { I: true, S: true, A: true, R: false },
    primitives: 4,
    turingComplete: false,
    symbolCount: null,
    description: "Untyped λ + type annotations. All terms normalize. No general recursion.",
    encoding: "λx:A.M",
    rewriteRules: ["(λx:A.M)N → M[x:=N]", "Type: (A→B)"],
    bisimQuotient: "Cartesian closed categories",
    color: "#e8af34",
    notable: "Curry-Howard: proofs in propositional logic",
    quotientClass: "CCC"
  },
  {
    id: "system-f",
    name: "System F",
    symbol: "λ2",
    family: "Lambda",
    carriers: { I: true, S: true, A: true, R: true },
    primitives: 5,
    turingComplete: false,
    symbolCount: null,
    description: "Polymorphic λ-calculus. Second-order types. Can encode all System T programs.",
    encoding: "ΛX.λx:X.x",
    rewriteRules: ["(ΛX.M)[A] → M[X:=A]", "(λx:A.M)N → M[x:=N]"],
    bisimQuotient: "Polymorphic CCC",
    color: "#fdab43",
    notable: "Girard/Reynolds — basis of ML/Haskell type systems",
    quotientClass: "Poly"
  },
  {
    id: "coc",
    name: "Calculus of Constructions",
    symbol: "CoC",
    family: "Lambda",
    carriers: { I: true, S: true, A: true, R: true },
    primitives: 6,
    turingComplete: false,
    symbolCount: null,
    description: "Dependent types + polymorphism. Types and terms unified. Basis of Coq/Lean.",
    encoding: "Π(x:A).B",
    rewriteRules: ["β-reduction", "η-reduction", "δ-reduction (definitions)"],
    bisimQuotient: "Locally cartesian closed categories",
    color: "#bb653b",
    notable: "Curry-Howard: proofs = programs, propositions = types",
    quotientClass: "ProofTheory"
  },
  {
    id: "coq",
    name: "Coq",
    symbol: "Coq",
    family: "Lambda",
    carriers: { I: true, S: true, A: true, R: true },
    primitives: 7,
    turingComplete: false,
    symbolCount: null,
    description: "Interactive theorem prover based on the Calculus of Inductive Constructions (CIC). Proofs are terms, propositions are types.",
    encoding: "Theorem id : forall A, A -> A. Proof. intros. exact x. Qed.",
    rewriteRules: ["β-reduction", "ι-reduction (inductive matches)", "δ-reduction (unfolding)", "ζ-reduction"],
    bisimQuotient: "Calculus of Inductive Constructions (CIC)",
    color: "#bb653b",
    notable: "Used to formalize the Feit-Thompson theorem and 4-color theorem",
    quotientClass: "ProofTheory"
  },
  {
    id: "lean",
    name: "Lean",
    symbol: "Lean",
    family: "Lambda",
    carriers: { I: true, S: true, A: true, R: true },
    primitives: 6,
    turingComplete: false,
    symbolCount: null,
    description: "Modern proof assistant and programming language based on dependent type theory. Extensively used for formalizing advanced mathematics.",
    encoding: "theorem my_id {α : Type} (x : α) : x = x := rfl",
    rewriteRules: ["β-reduction", "ι-reduction", "δ-reduction", "Quotient reduction"],
    bisimQuotient: "Dependent Type Theory with quotients",
    color: "#dd6974",
    notable: "Mathlib project contains the largest formalization of modern mathematics",
    quotientClass: "ProofTheory"
  },
  // === REWRITING SYSTEMS ===
  {
    id: "term-rewriting",
    name: "Term Rewriting",
    symbol: "TRS",
    family: "Rewriting",
    carriers: { I: false, S: true, A: true, R: true },
    primitives: 2,
    turingComplete: true,
    symbolCount: null,
    description: "Signature of function symbols + rewrite rules l → r. Covers all computation.",
    encoding: "f(x,y) → g(y,x)",
    rewriteRules: ["l → r (contextual, left-linear)"],
    bisimQuotient: "Word problem in algebra",
    color: "#5591c7",
    notable: "Knuth-Bendix completion as normalization procedure",
    quotientClass: "Rewriting"
  },
  {
    id: "string-rewriting",
    name: "String Rewriting",
    symbol: "SRS",
    family: "Rewriting",
    carriers: { I: false, S: true, A: false, R: true },
    primitives: 2,
    turingComplete: true,
    symbolCount: null,
    description: "Words over alphabet + string replacement rules. Semi-Thue systems.",
    encoding: "ab → ba",
    rewriteRules: ["u → v (substring replacement)"],
    bisimQuotient: "Monoid presentations",
    color: "#5591c7",
    notable: "Simplest Turing-complete rewriting — used in Post's theorem",
    quotientClass: "Rewriting"
  },
  // === PROCESS CALCULI ===
  {
    id: "pi-calculus",
    name: "π-calculus",
    symbol: "π",
    family: "Process",
    carriers: { I: true, S: true, A: true, R: true },
    primitives: 5,
    turingComplete: true,
    symbolCount: null,
    description: "Mobile processes communicating over channels. Names are first-class.",
    encoding: "x̄⟨y⟩.P | x(z).Q",
    rewriteRules: ["x̄⟨y⟩.P | x(z).Q → P | Q[z:=y]"],
    bisimQuotient: "Bisimilarity quotient (Milner)",
    color: "#d163a7",
    notable: "Basis of session types and distributed systems theory",
    quotientClass: "Process"
  },
  {
    id: "ccs",
    name: "CCS",
    symbol: "CCS",
    family: "Process",
    carriers: { I: true, S: true, A: true, R: true },
    primitives: 4,
    turingComplete: true,
    symbolCount: null,
    description: "Calculus of Communicating Systems. Milner 1980. Synchronous communication.",
    encoding: "a.P | ā.Q → P | Q",
    rewriteRules: ["a.P | ā.Q →τ P | Q"],
    bisimQuotient: "Strong bisimilarity",
    color: "#d163a7",
    notable: "First formal foundation for behavioral equivalence",
    quotientClass: "Process"
  },
  // === LOGIC / PROOF SYSTEMS ===
  {
    id: "prop-logic",
    name: "Prop. Logic",
    symbol: "PL",
    family: "Logic",
    carriers: { I: true, S: false, A: true, R: false },
    primitives: 4,
    turingComplete: false,
    symbolCount: null,
    description: "Boolean formulas + modus ponens. Decidable. NP-complete satisfiability.",
    encoding: "A → B, A ⊢ B",
    rewriteRules: ["Modus Ponens", "Resolution"],
    bisimQuotient: "Boolean algebra",
    color: "#437a22",
    notable: "Curry-Howard: simply typed λ-calculus",
    quotientClass: "CCC"
  },
  {
    id: "fol",
    name: "First-Order Logic",
    symbol: "FOL",
    family: "Logic",
    carriers: { I: true, S: true, A: true, R: true },
    primitives: 7,
    turingComplete: false,
    symbolCount: null,
    description: "Quantifiers over individuals. Semi-decidable. Gödel complete, arithmetic incomplete.",
    encoding: "∀x.∃y. P(x,y)",
    rewriteRules: ["∀-elim", "∃-intro", "Unification"],
    bisimQuotient: "Lindström's theorem",
    color: "#437a22",
    notable: "Gödel incompleteness — limits of formal provability",
    quotientClass: "ProofTheory"
  },
  {
    id: "linear-logic",
    name: "Linear Logic",
    symbol: "LL",
    family: "Logic",
    carriers: { I: true, S: true, A: true, R: true },
    primitives: 8,
    turingComplete: false,
    symbolCount: null,
    description: "Resources used exactly once. ! (bang) restores classical weakening/contraction.",
    encoding: "A ⊗ B, A ⅋ B, !A",
    rewriteRules: ["Cut elimination", "Resource management"],
    bisimQuotient: "∗-autonomous categories",
    color: "#437a22",
    notable: "Girard 1987 — corresponds to BCKW combinators",
    quotientClass: "Linear"
  },
  {
    id: "sequent-calculus",
    name: "Sequent Calculus",
    symbol: "LK/LJ",
    family: "Logic",
    carriers: { I: true, S: false, A: true, R: false },
    primitives: 12,
    turingComplete: false,
    symbolCount: null,
    description: "Gentzen's logical system representing proofs as trees of sequents. Separates structural rules (weakening, contraction, exchange) from logical rules.",
    encoding: "Γ ⊢ Δ",
    rewriteRules: ["Cut Elimination (Hauptsatz)", "Logical rules"],
    bisimQuotient: "Classical / Intuitionistic logic",
    color: "#437a22",
    notable: "Cut elimination theorem corresponds to normalization / execution",
    quotientClass: "ProofTheory"
  },
  {
    id: "isabelle-isar",
    name: "Isabelle/Isar",
    symbol: "Isar",
    family: "Logic",
    carriers: { I: true, S: true, A: true, R: true },
    primitives: 3,
    turingComplete: true,
    symbolCount: null,
    description: "Generic proof assistant based on Isabelle/Pure meta-logic with Isar structured proof language. Supports multiple object logics (HOL, ZF).",
    encoding: "theorem A: \"P ==> P\" by (rule assms)",
    rewriteRules: ["Resolution", "Rewriting (simp)", "Backchaining"],
    bisimQuotient: "LCF-style kernel / Higher-order logic",
    color: "#437a22",
    notable: "LCF kernel architecture ensures absolute proof correctness",
    quotientClass: "ProofTheory"
  },
  // === AUTOMATA ===
  {
    id: "turing-machine",
    name: "Turing Machine",
    symbol: "TM",
    family: "Automata",
    carriers: { I: true, S: true, A: false, R: true },
    primitives: 5,
    turingComplete: true,
    symbolCount: null,
    description: "Tape + head + state table. The universal reference for computability.",
    encoding: "δ(q,a) = (q',b,L/R)",
    rewriteRules: ["State transition + tape rewrite"],
    bisimQuotient: "Computable functions",
    color: "#006494",
    notable: "Church-Turing thesis — defines the boundary of computation",
    quotientClass: "Rewriting"
  },
  {
    id: "lambda-mu",
    name: "λμ-calculus",
    symbol: "λμ",
    family: "Lambda",
    carriers: { I: true, S: true, A: true, R: true },
    primitives: 5,
    turingComplete: true,
    symbolCount: null,
    description: "λ-calculus + control operators (call/cc). Parigot 1992. Classical logic proofs.",
    encoding: "μα.⟨α|M⟩",
    rewriteRules: ["(λx.M)N → M[x:=N]", "μα.⟨α|M⟩N → μα.⟨α|MN⟩"],
    bisimQuotient: "Classical sequent calculus",
    color: "#dd6974",
    notable: "Curry-Howard for classical logic — call/cc = excluded middle",
    quotientClass: "TuringFunctional"
  },
  // === ISAR KERNEL ===
  {
    id: "ISAR",
    name: "ISAR Kernel",
    symbol: "I·R·A·S",
    family: "Substrate",
    carriers: { I: true, S: true, A: true, R: true },
    primitives: 4,
    turingComplete: true,
    symbolCount: null,
    description: "Invariant substrate. U(K) = I·R·A·S. Generates computational space itself. All other systems are Futamura projections within it.",
    encoding: "[[0,0,0,0],[0,0,0,0],[1,1,0,0],[0,0,0,0]]",
    rewriteRules: ["NORM = S·I", "APP = A·R", "COMP = R·A·S"],
    bisimQuotient: "Terminal object / Final coalgebra",
    color: "#4f98a3",
    notable: "Ontological ground — not a dialect but the substrate all dialects inhabit",
    quotientClass: "Substrate"
  }
];

if (typeof module !== 'undefined') module.exports = SYSTEMS;
