"""gen_x86_map â€” synthesize the x86-64 win64 assembly map (.phi)
from the mined ISA row data.

The translator treats host/isa_x86_64.py's ENCS/INSN/REG tables as
the source of truth:

  - each ENCS alternative          -> one enc2 clause
  - each field op                  -> a call into shared field rels
  - each predicate                 -> a flag rel (0/1), and later
    alternatives carry earlier preds' negations â€” ordered
    alternatives stay exclusive without negation-as-failure
  - enc2_len mirrors enc2          -> pass1's label->offset rows;
    widths are label-independent (rel is always 4 bytes, imm/disp
    widths depend only on operand values)

Numbers are corpus-native: immediates ('i(nl)), mem disps, pcs and
symtab values are LE nibble lists; fixups compute
disp = target_rva - (trva + pc + len) through nibble_add/nibble_sub
â€” two's-complement wrap by construction.

Src operand terms:
  reg name   -> bare sym ('rax, 'ecx, 'al)
  imm        -> 'i(nl)        canonical nl8 (|v| < 2^31) or nl16
  mem        -> 'm(base, nl8) ('m', basereg, disp)
  rip-rel    -> 'p(name)      symtab-resolved target
  rel32      -> 'l(name)      label-resolved target
  label item -> 'label(name)

Usage:  python host/gen_x86_map.py > phi2/maps/assemble_x86_win64.phi
"""
from __future__ import annotations

import os
import sys

_HOST = os.path.dirname(os.path.abspath(__file__))
if _HOST not in sys.path:
    sys.path.insert(0, _HOST)

import isa_x86_64 as isa            # noqa: E402
import target_pe64                  # noqa: E402
import routines_x86_64_win64 as rts  # noqa: E402

IMPORTS = rts.IMPORTS
SLOTS = rts.DATA_SLOTS
SYMS = target_pe64.symbols(IMPORTS, SLOTS)
TRVA = target_pe64.text_rva(IMPORTS, SLOTS)


def nl(v: int, n: int = 8) -> str:
    """LE nibble-list literal."""
    return "[" + ", ".join(f"ATOM(4,{(v >> (4 * i)) & 0xF})"
                           for i in range(n)) + "]"


def bl(bs) -> str:
    return "[" + ", ".join(f"ATOM(8,{b})" for b in bs) + "]"


def opbytes(op: int):
    if op > 0xFFFF:
        return [(op >> 16) & 0xFF, (op >> 8) & 0xFF, op & 0xFF]
    if op > 0xFF:
        return [(op >> 8) & 0xFF, op & 0xFF]
    return [op]


class Gen:
    def __init__(self):
        self.n = 0

    def v(self):
        self.n += 1
        return f"v{self.n}"


# ======================================================================
# static sections
# ======================================================================

HEADER = """;; assemble_x86_win64 â€” GENERATED by host/gen_x86_map.py
;; Do not hand-edit: synthesized from the mined ISA rows
;; (host/isa_x86_64.py ENCS/INSN/REG tables) and the declared PE64
;; layout (host/target_pe64.py symbols/text_rva).
;;
;; uses: ../std/arith_nibble_carry, ../std/arith_peano_succ, ../std/lists_append_mapfold, ../std/lists_member_assoc, ../std/unify_terms_core, ../std/meta_call_run
;;
;; Two-pass pc-threaded assembly:
;;   pass1<ops, pc8> = labs        label -> section-offset (nl8)
;;   assemble2<ops, labs, pc8>     enc2 with 'l/'p fixups:
;;     'l: disp = (trva + off) - (trva + pc + len)
;;     'p: disp = symtab -       (trva + pc + len)
;; nibble-domain subtraction: wrap IS two's-complement.
"""

NIBBLE = """
;; ---------- nibble arithmetic ----------

nibble_pred : <n: T[4]> <-> <PAIR(p, w)> where {
%%NIBBLE_PRED%%
}

nibble_sub_b : <a: T[4], b: T[4]> <-> <PAIR(d, w)> shape self where {
  | b = ATOM(4,0) { d = a   w = ATOM(4,0) }
  | fresh(bp, s1, w1, s2, w2, wo) {
      b != ATOM(4,0)
      nibble_pred<b> = PAIR(bp, _)
      nibble_pred<a> = PAIR(s1, w1)
      nibble_sub_b<s1, bp> = PAIR(s2, w2)
      bor<w1, w2> = wo
      d = s2   w = wo
    }
}

nibble_half_sub : <a: T[4], b: T[4], cin: T[4]> <-> <PAIR(d, cout)> where {
  | fresh(s1, w1, w2) {
      nibble_sub_b<a, b> = PAIR(s1, w1)
      nibble_sub_b<s1, cin> = PAIR(d, w2)
      bor<w1, w2> = cout
    }
}

nibble_sub : <a, b, br: T[4]> <-> <result> shape self where {
  | a = [] & b = [] { result = [] }
  | fresh(an, bn, dn, cn, at, bt, rest) {
      head<a> = an   tail<a> = at
      head<b> = bn   tail<b> = bt
      nibble_half_sub<an, bn, br> = PAIR(dn, cn)
      nibble_sub<at, bt, cn> = rest
      result = PAIR(dn, rest)
    }
}

;; local ripple adder â€” corpus nibble_add_b clause2 has no b!=0
;; guard, so it yields a phantom wrap sol on re-pull; this variant is
;; sol-disjoint (backtracking-safe).
nadd_b : <a: T[4], b: T[4]> <-> <PAIR(d, w)> shape self where {
  | b = ATOM(4,0) { d = a   w = ATOM(4,0) }
  | fresh(bp, s1, w1, s2, w2, wo) {
      b != ATOM(4,0)
      nibble_succ<bp> = PAIR(b, _)
      nibble_succ<a> = PAIR(s1, w1)
      nadd_b<s1, bp> = PAIR(s2, w2)
      bor<w1, w2> = wo
      d = s2   w = wo
    }
}

nadd_h : <a: T[4], b: T[4], cin: T[4]> <-> <PAIR(d, cout)> where {
  | fresh(s1, w1, w2) {
      nadd_b<a, b> = PAIR(s1, w1)
      nadd_b<s1, cin> = PAIR(d, w2)
      bor<w1, w2> = cout
    }
}

nl_add : <a, b, cin: T[4]> <-> <result> shape self where {
  | a = [] & b = [] { result = [] }
  | fresh(an, bn, dn, cn, at, bt, rest) {
      head<a> = an   tail<a> = at
      head<b> = bn   tail<b> = bt
      nadd_h<an, bn, cin> = PAIR(dn, cn)
      nl_add<at, bt, cn> = rest
      result = PAIR(dn, rest)
    }
}

len_nl : <xs> <-> <nl> shape self where {
  | xs = [] { nl = %%NL0%% }
  | fresh(h, t, n1) {
      xs = PAIR(h, t)
      len_nl<t> = n1
      nl_add<n1, %%NL1%%, ATOM(4,0)> = nl
    }
}

shl4 : <h: T[4]> <-> <v> where {
%%SHL4%%
}

bplus : <x, n> <-> <r> shape self where {
  | n = ATOM(4,0) { r = x }
  | fresh(n1, x1) {
      n != ATOM(4,0)
      nibble_pred<n> = PAIR(n1, _)
      x1 = ATOM(8, x+1)
      bplus<x1, n1> = r
    }
}

nibs2bytes : <nl> <-> <bs> shape self where {
  | nl = [] { bs = [] }
  | fresh(lo, hi, rest, sh, b, rb) {
      nl = PAIR(lo, PAIR(hi, rest))
      shl4<hi> = sh   bplus<sh, lo> = b
      nibs2bytes<rest> = rb
      bs = PAIR(b, rb)
    }
}

;; ---------- predicates as flags (no negation-as-failure) ----------

;; nlz/nlf: partial all-zero / all-F tests (guard use only)
nlz : <nl> <-> <ok> shape self where {
  | nl = [] { ok = 1 }
  | fresh(t) { nl = PAIR(ATOM(4,0), t)   nlz<t> = _   ok = 1 }
}

nlf : <nl> <-> <ok> shape self where {
  | nl = [] { ok = 1 }
  | fresh(t) { nl = PAIR(ATOM(4,15), t)   nlf<t> = _   ok = 1 }
}

;; total flag variants â€” single-sol, usable as 0/1 values
nlzf : <nl> <-> <f> shape self where {
  | nl = [] { f = 1 }
  | fresh(t, r) { nl = PAIR(ATOM(4,0), t)   nlzf<t> = f }
  | fresh(h, t) { nl = PAIR(h, t)   h != ATOM(4,0)   f = 0 }
}

nlff : <nl> <-> <f> shape self where {
  | nl = [] { f = 1 }
  | fresh(t, r) { nl = PAIR(ATOM(4,15), t)   nlff<t> = f }
  | fresh(h, t) { nl = PAIR(h, t)   h != ATOM(4,15)   f = 0 }
}

lon4 : <n> <-> <ok> where {
%%LON4%%
}
hin4 : <n> <-> <ok> where {
%%HIN4%%
}

lon4f : <n> <-> <f> where {
%%LON4F%%
}
hin4f : <n> <-> <f> where {
%%HIN4F%%
}

and2 : <a, b> <-> <r> where {
  | a = 0 { r = 0 }
  | a != 0 & b = 0 { r = 0 }
  | a != 0 & b != 0 { r = 1 }
}

;; se8f<nl> = 1 iff the canonical signed nl fits i8
;; (nibbles 2.. == sign extension of nibble 1) â€” total
se8f : <nl> <-> <f> where {
  | fresh(n0, n1, rest, z, ff, lo, hi, a, b) {
      nl = PAIR(n0, PAIR(n1, rest))
      nlzf<rest> = z   nlff<rest> = ff
      lon4f<n1> = lo   hin4f<n1> = hi
      and2<z, lo> = a   and2<ff, hi> = b
      or2<a, b> = f
    }
}

;; i32f: canonical rep is nl8 iff value fits signed 32
i32f : <nl> <-> <f> where {
  | nl = [_, _, _, _, _, _, _, _] { f = 1 }
  | nl = [_, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _] { f = 0 }
}

accf : <o> <-> <f> where {
  | fresh(lo, hi) {
      regc<o> = PAIR(lo, hi)   lo = ATOM(4,0)   hi = ATOM(4,0)
      f = 1
    }
  | fresh(lo, hi) {
      regc<o> = PAIR(lo, hi)   lo != ATOM(4,0)   f = 0
    }
  | fresh(lo, hi) {
      regc<o> = PAIR(lo, hi)   hi != ATOM(4,0)   f = 0
    }
  | o = PAIR(_, _) { f = 0 }
}

or2 : <a, b> <-> <r> where {
  | a = 0 & b = 0 { r = 0 }
  | a = 0 & b != 0 { r = 1 }
  | a != 0 { r = 1 }
}
"""


def reg_tables() -> str:
    out = [";; ---------- register tables ----------",
           ";; regc: name -> (code&7, code>>3); all width families share",
           ";; the code space (rax/eax/al -> 0).",
           "regc : <r> <-> <PAIR(lo, hi)> where {"]
    seen = set()
    for d in (isa.REG64, isa.REG32, isa.REG8):
        for name, c in sorted(d.items(), key=lambda kv: (kv[1], kv[0])):
            if name in seen:
                continue
            seen.add(name)
            out.append(f"  | r = '{name} {{ lo = ATOM(4,{c & 7})   "
                       f"hi = ATOM(4,{c >> 3}) }}")
    out.append("}\n")
    out.append(";; rfx: regfield contribution ((code&7)<<3)")
    out.append("rfx : <r> <-> <v> where {")
    seen.clear()
    for d in (isa.REG64, isa.REG32, isa.REG8):
        for name, c in sorted(d.items(), key=lambda kv: (kv[1], kv[0])):
            if name in seen:
                continue
            seen.add(name)
            out.append(f"  | r = '{name} {{ v = {(c & 7) << 3} }}")
    out.append("}\n")
    # rex-need: byte regs with code>=4 force REX even when bits are 0
    needing = {n for n, c in isa.REG8.items() if c >= 4}
    out.append(";; rnx1: operand needs a REX byte even when v==0x40")
    out.append("rnx1 : <o> <-> <f> where {")
    for n in sorted(needing):
        out.append(f"  | o = '{n} {{ f = 1 }}")
    for d in (isa.REG64, isa.REG32, isa.REG8):
        for name in sorted(d):
            if name not in needing:
                out.append(f"  | o = '{name} {{ f = 0 }}")
    out.append("  | o = PAIR(_, _) { f = 0 }")
    out.append("}\n")
    out.append("""rnx : <ops> <-> <f> shape self where {
  | ops = [] { f = 0 }
  | fresh(h, t, fh, ft) {
      ops = PAIR(h, t)   rnx1<h> = fh   rnx<t> = ft   or2<fh, ft> = f
    }
}

;; operand -> code lo3 / hi1 (mem base for 'm, 0 for 'p/'l)
plo8 : <o> <-> <lo8> where {
  | fresh(b, lo) {
      regc<o> = PAIR(lo, _)   c48<lo> = lo8
    }
  | fresh(b, d, lo) {
      o = 'm(b, d)   regc<b> = PAIR(lo, _)   c48<lo> = lo8
    }
}
phi : <o> <-> <hi> where {
  | fresh(d) { regc<o> = PAIR(d, hi) }
  | fresh(b, d) { o = 'm(b, d)   regc<b> = PAIR(_, hi) }
  | fresh(n) { o = 'p(n)   hi = ATOM(4,0) }
  | fresh(n) { o = 'l(n)   hi = ATOM(4,0) }
}

;; c48: nibble atom -> same value as a byte atom
c48 : <n: T[4]> <-> <b> where {
%%C48%%
}""")
    return "\n".join(out)


FIELD_RELS = """
;; ---------- field relations ----------

;; rex emission: suppress 0x40 unless an operand needs it
rex_emit : <v, ops> <-> <bs> where {
  | v != ATOM(8,64) { bs = [v] }
  | fresh(f) { v = ATOM(8,64)   rnx<ops> = f   f = 1   bs = [v] }
  | fresh(f) { v = ATOM(8,64)   rnx<ops> = f   f = 0   bs = [] }
}

;; hi bit -> REX.R contribution (*4, as nibble for bplus)
hx4 : <h: T[4]> <-> <v> where {
  | h = ATOM(4,0) { v = ATOM(4,0) }
  | h = ATOM(4,1) { v = ATOM(4,4) }
}

;; rflo: (regfield<<3) + rmlo â€” 64 declared rows; replaces builtin
;; add (re-pull unsafe) in modrm/modrm-mem emission.
rflo : <rf, lo> <-> <s> where {
%%RFLO%%
}

;; modrm mod=11: 0xC0 + regfield + rmlo   (rf, lo as byte atoms)
mrm_rr : <rf, lo> <-> <m> where {
  | fresh(s) { rflo<rf, lo> = s   m = ATOM(8, s+0xC0) }
}

;; modrm rip: mod=00 rm=101
mrm_rip : <rf> <-> <m> where {
  | fresh(s) { rflo<rf, ATOM(8,5)> = s   m = s }
}

;; mem_f<rf, base, dnl> = PAIR(head, dispbytes)
;; rf = regfield<<3 (byte atom); exclusive cases mirror _mem_modrm:
;;   disp0 & lo!=5 -> mod00 ; disp0 & lo==5 -> mod01 disp8=0
;;   fits-i8 -> mod01 disp8 ; else mod10 disp32 ; SIB iff lo==4.
mem_f : <rf, base, dnl> <-> <PAIR(mh, db)> where {
  | fresh(lo, hi, s, s0, z) {
      regc<base> = PAIR(lo, hi)   nlz<dnl> = _
      lo != ATOM(4,4)   lo != ATOM(4,5)
      c48<lo> = s0   rflo<rf, s0> = s
      mh = [s]   db = []
    }
  | fresh(lo, hi, s, s0, z) {
      regc<base> = PAIR(lo, hi)   nlz<dnl> = _
      lo = ATOM(4,4)
      c48<lo> = s0   rflo<rf, s0> = s
      mh = [s, 0x24]   db = []
    }
  | fresh(lo, hi, s, s0, z) {
      regc<base> = PAIR(lo, hi)   nlz<dnl> = _
      lo = ATOM(4,5)
      c48<lo> = s0   rflo<rf, s0> = s
      mh = [ATOM(8, s+64)]   db = [0]
    }
  | fresh(lo, hi, s, s0, d0, d1, sh, d8) {
      regc<base> = PAIR(lo, hi)
      nlzf<dnl> = 0   se8f<dnl> = 1
      lo != ATOM(4,4)
      c48<lo> = s0   rflo<rf, s0> = s
      dnl = PAIR(d0, PAIR(d1, _))
      shl4<d1> = sh   bplus<sh, d0> = d8
      mh = [ATOM(8, s+64)]   db = [d8]
    }
  | fresh(lo, hi, s, s0, d0, d1, sh, d8) {
      regc<base> = PAIR(lo, hi)
      nlzf<dnl> = 0   se8f<dnl> = 1
      lo = ATOM(4,4)
      c48<lo> = s0   rflo<rf, s0> = s
      dnl = PAIR(d0, PAIR(d1, _))
      shl4<d1> = sh   bplus<sh, d0> = d8
      mh = [ATOM(8, s+64), 0x24]   db = [d8]
    }
  | fresh(lo, hi, s, s0, db4) {
      regc<base> = PAIR(lo, hi)
      nlzf<dnl> = 0   se8f<dnl> = 0
      lo != ATOM(4,4)
      c48<lo> = s0   rflo<rf, s0> = s
      nibs2bytes<dnl> = db4
      mh = [ATOM(8, s+128)]   db = db4
    }
  | fresh(lo, hi, s, s0, db4) {
      regc<base> = PAIR(lo, hi)
      nlzf<dnl> = 0   se8f<dnl> = 0
      lo = ATOM(4,4)
      c48<lo> = s0   rflo<rf, s0> = s
      nibs2bytes<dnl> = db4
      mh = [ATOM(8, s+128), 0x24]   db = db4
    }
}

;; immediates: 'i(nl) â€” width by nl length
im8 : <nl> <-> <bs> where {
  | fresh(n0, n1, sh, b) {
      nl = PAIR(n0, PAIR(n1, _))
      shl4<n1> = sh   bplus<sh, n0> = b   bs = [b]
    }
}
im32 : <nl> <-> <bs> where { nibs2bytes<nl> = bs }
im64 : <nl> <-> <bs> where { nibs2bytes<nl> = bs }

;; relfix<o, labs, acc, pcva8> â€” trailing rel32:
;;   end = pcva + len(acc) + 4 ;  disp = target - end
relfix : <o, labs, acc, pcva8> <-> <db> where {
  | fresh(n, off, t8, l8, e1, end, dnl) {
      o = 'l(n)
      assoc<n, labs> = off
      nl_add<%%TRVA%%, off, ATOM(4,0)> = t8
      len_nl<acc> = l8
      nl_add<pcva8, l8, ATOM(4,0)> = e1
      nl_add<e1, %%NL4%%, ATOM(4,0)> = end
      nibble_sub<t8, end, ATOM(4,0)> = dnl
      nibs2bytes<dnl> = db
    }
  | fresh(n, t8, l8, e1, end, dnl) {
      o = 'p(n)
      symtab<n> = t8
      len_nl<acc> = l8
      nl_add<pcva8, l8, ATOM(4,0)> = e1
      nl_add<e1, %%NL4%%, ATOM(4,0)> = end
      nibble_sub<t8, end, ATOM(4,0)> = dnl
      nibs2bytes<dnl> = db
    }
}
"""


def symtab_rel() -> str:
    out = [";; ---------- declared layout (target_pe64.symbols) ----------",
           "symtab : <name> <-> <nl8> where {"]
    for name, v in sorted(SYMS.items()):
        out.append(f"  | name = '{name} {{ nl8 = {nl(v)} }}")
    out.append("}")
    return "\n".join(out)


# ======================================================================
# generated rels
# ======================================================================

def rex_rels() -> str:
    """One rel per distinct rex role-tuple: rex_<roles><vb, ops...>.
    vb is the row-constant base byte 0x40|w<<3 â€” the 'w' role reads the
    row's W flag, so callers inject it (w=0 rows must emit 0x4x)."""
    sigs = {}
    for form, alts in isa.ENCS.items():
        for conds, tmpl in alts:
            for f in tmpl:
                if f[0] == "rex":
                    sigs.setdefault(tuple(f[1:]), None)
    out = [";; ---------- generated rex rels ----------"]
    for roles in sorted(sigs):
        name = "rex_" + "_".join(roles) if roles else "rex_none"
        idxs = sorted({int(r[1:]) for r in roles if r != "w"})
        args = ", ".join(["vb"] + [f"o{i}" for i in idxs])
        opslist = "[" + ", ".join(f"o{i}" for i in idxs) + "]"
        g = Gen()
        lines = []
        acc = "vb"
        for r in roles:
            if r == "w":
                continue
            o = f"o{r[1:]}"
            h = g.v()
            lines.append(f"      phi<{o}> = {h}")
            nv = g.v()
            if r[0] == "R":
                hv = g.v()
                lines.append(f"      hx4<{h}> = {hv}")
                lines.append(f"      bplus<{acc}, {hv}> = {nv}")
            else:
                lines.append(f"      bplus<{acc}, {h}> = {nv}")
            acc = nv
        fvars = ", ".join(f"v{i}" for i in range(1, g.n + 1))
        head = f"{name} : <{args}> <-> <bs> where {{"
        out.append(head)
        if fvars:
            out.append(f"  | fresh({fvars}) {{")
            out.extend(lines)
            out.append(f"      rex_emit<{acc}, {opslist}> = bs")
            out.append("    }")
        else:
            out.append(f"  | fresh(d) {{ rex_emit<{acc}, "
                       f"{opslist}> = bs }}")
        out.append("}")
        out.append("")
    return "\n".join(out)


def _rex_call(roles, w, g):
    """Emit the rex_<roles> call goal for a field; returns the out var."""
    name = ("rex_" + "_".join(roles)) if roles else "rex_none"
    idxs = sorted({int(r[1:]) for r in roles if r != "w"})
    vb = 64 + 8 * (w if "w" in roles else 0)
    callargs = ", ".join([f"ATOM(8,{vb})"]
                         + [f"o{i}" for i in idxs])
    nv = g.v()
    return f"      {name}<{callargs}> = {nv}", nv


def _operand_arity(form: str) -> int:
    """Max operand index referenced by the form's rows/preds."""
    hi = -1
    import re
    for conds, tmpl in isa.ENCS[form]:
        for c in conds:
            hi = max(hi, c[1])
        for f in tmpl:
            for a in f[1:]:
                if isinstance(a, str):
                    for m in re.findall(r"(?:reg|rm|mem|[RB])(\d+)",
                                        a):
                        hi = max(hi, int(m))
                if f[0] in ("imm", "rel"):
                    hi = max(hi, f[-1])
    return hi + 1


def _pred_goals(conds, negate, g, goals):
    """Emit flag goals for a pred list; negate selects the 0-branch."""
    for c in conds:
        pn, idx = c[0], c[1]
        want = "0" if negate else "1"
        if pn in ("i8", "i32"):
            rel = "se8f" if pn == "i8" else "i32f"
            nlv = g.v()
            goals.append(f"      o{idx} = 'i({nlv})")
            goals.append(f"      {rel}<{nlv}> = {want}")
        elif pn == "acc":
            goals.append(f"      accf<o{idx}> = {want}")
        else:
            raise ValueError(f"pred {pn}")


def enc2_rels() -> str:
    out = [";; ---------- enc2: form x alternative -> clause ----------",
           "enc2 : <op, labs, pc8> <-> <bytes> where {"]
    for form, alts in isa.ENCS.items():
        _, op, w, ext, _ = isa.FORMS[form]
        arity = _operand_arity(form)
        pat = ("'op('" + form +
               (", " + ", ".join(f"o{i}" for i in range(arity))
                if arity else "") + ")")
        earlier = []
        for conds, tmpl in alts:
            g = Gen()
            goals = [f"      op = {pat}"]
            _pred_goals(conds, False, g, goals)
            for c in earlier:
                _pred_goals([c], True, g, goals)
            needs_pcva = any(f[0] == "rel" for f in tmpl)
            pcva = None
            if needs_pcva:
                pcva = g.v()
                goals.insert(1, "      nl_add<" + nl(TRVA) +
                             f", pc8, ATOM(4,0)> = {pcva}")
            acc = "[]"
            dispvar = None
            for f in tmpl:
                nv = g.v()
                if f[0] == "raw":
                    goals.append(f"      {nv} = {bl(f[1:])}")
                elif f[0] == "op":
                    v = f[1] if len(f) > 1 else op
                    goals.append(f"      {nv} = {bl(opbytes(v))}")
                elif f[0] == "oprd":
                    lo = g.v()
                    goals.append(
                        f"      regc<o0> = PAIR({lo}, _)")
                    b = g.v()
                    goals.append(
                        f"      bplus<ATOM(8,{op}), {lo}> = {b}")
                    goals.append(f"      {nv} = [{b}]")
                elif f[0] == "rex":
                    call, nv = _rex_call(f[1:], w, g)
                    goals.append(call)
                elif f[0] == "modrm":
                    reg, rm = f[1], f[2]
                    if isinstance(reg, int):
                        rf = f"ATOM(8,{reg << 3})"
                    elif reg == "ext":
                        rf = f"ATOM(8,{ext << 3})"
                    else:
                        rf = g.v()
                        goals.append(f"      rfx<o{reg[3:]}> = {rf}")
                    if rm == "rip":
                        b = g.v()
                        goals.append(f"      mrm_rip<{rf}> = {b}")
                        goals.append(f"      {nv} = [{b}]")
                    elif rm.startswith("rm"):
                        lo8 = g.v()
                        b = g.v()
                        goals.append(
                            f"      plo8<o{rm[2:]}> = {lo8}")
                        goals.append(
                            f"      mrm_rr<{rf}, {lo8}> = {b}")
                        goals.append(f"      {nv} = [{b}]")
                    else:  # memI
                        bv, dv = g.v(), g.v()
                        dlv = g.v()
                        goals.append(
                            f"      o{rm[3:]} = 'm({bv}, {dv})")
                        goals.append(
                            f"      mem_f<{rf}, {bv}, {dv}> = "
                            f"PAIR({nv}, {dlv})")
                        dispvar = dlv
                elif f[0] == "disp":
                    nv = dispvar
                elif f[0] == "imm":
                    nlv = g.v()
                    goals.append(f"      o{f[2]} = 'i({nlv})")
                    fn = {"i8": "im8", "i32": "im32",
                          "i64": "im64"}[f[1]]
                    goals.append(f"      {fn}<{nlv}> = {nv}")
                elif f[0] == "rel":
                    goals.append(
                        f"      relfix<o{f[1]}, labs, {acc}, "
                        f"{pcva}> = {nv}")
                else:
                    raise ValueError(f)
                av = g.v()
                goals.append(f"      append<{acc}, {nv}> = {av}")
                acc = av
            goals.append(f"      bytes = {acc}")
            ovars = ", ".join(f"o{i}" for i in range(arity))
            fvars = ", ".join(f"v{i}" for i in range(1, g.n + 1))
            decls = ", ".join(x for x in (ovars, fvars) if x)
            out.append(f"  | fresh({decls}) {{")
            out.extend(goals)
            out.append("    }")
            earlier.extend(conds)
    out.append("}")
    return "\n".join(out)


def enc2_len_rels() -> str:
    """Length-only mirror of enc2: same alt selection, byte counts
    instead of bytes.  rel fields are always 4; mem disp/rex widths
    discriminate on the same data as enc2."""
    out = [";; ---------- enc2_len: same selection, lengths ----------",
           "enc2_len : <op> <-> <n8> where {"]
    for form, alts in isa.ENCS.items():
        _, op, w, ext, _ = isa.FORMS[form]
        arity = _operand_arity(form)
        pat = ("'op('" + form +
               (", " + ", ".join(f"o{i}" for i in range(arity))
                if arity else "") + ")")
        earlier = []
        for conds, tmpl in alts:
            # mem operand positions needing disp-case splits â€”
            # the same exclusive 7-way partition as mem_f:
            # k0 nlz lo!45 ->1; k1 nlz lo4 ->2; k2 nlz lo5 ->2;
            # k3 nz&se8 lo!4 ->2; k4 nz&se8 lo4 ->3;
            # k5 nz&!se8 lo!4 ->5; k6 nz&!se8 lo4 ->6
            memis = [f[2] for f in tmpl
                     if f[0] == "modrm" and str(f[2]).startswith("mem")]
            cases = [(None, 0)] if not memis else \
                [(m, k) for m in memis for k in range(7)]
            for memi, k in cases:
                g = Gen()
                goals = [f"      op = {pat}"]
                _pred_goals(conds, False, g, goals)
                for c in earlier:
                    _pred_goals([c], True, g, goals)
                acc = nl(0)
                dispvar = None
                for f in tmpl:
                    if f[0] == "raw":
                        add = len(f[1:])
                    elif f[0] == "op":
                        v = f[1] if len(f) > 1 else op
                        add = len(opbytes(v))
                    elif f[0] == "oprd":
                        add = 1
                    elif f[0] == "rex":
                        # data-dependent â€” measure actual emission
                        call, nv = _rex_call(f[1:], w, g)
                        goals.append(call)
                        lv = g.v()
                        goals.append(f"      len_nl<{nv}> = {lv}")
                        av = g.v()
                        goals.append(
                            f"      nl_add<{acc}, {lv}, "
                            f"ATOM(4,0)> = {av}")
                        acc = av
                        continue
                    elif f[0] == "modrm":
                        rm = f[2]
                        if rm.startswith("mem"):
                            # case k: 0=disp0 lo!=4,5; 1=disp0 lo4;
                            # 2=se8; 3=se8 lo4; 4=disp32; 5=disp32 lo4
                            bv, dv = g.v(), g.v()
                            lov = g.v()
                            goals.append(
                                f"      o{rm[3:]} = 'm({bv}, {dv})")
                            goals.append(
                                f"      regc<{bv}> = "
                                f"PAIR({lov}, _)")
                            if k == 0:
                                goals.append(f"      nlz<{dv}> = _")
                                goals.append(
                                    f"      {lov} != ATOM(4,4)")
                                goals.append(
                                    f"      {lov} != ATOM(4,5)")
                                add = 1
                            elif k == 1:
                                goals.append(f"      nlz<{dv}> = _")
                                goals.append(
                                    f"      {lov} = ATOM(4,4)")
                                add = 2
                            elif k == 2:
                                goals.append(f"      nlz<{dv}> = _")
                                goals.append(
                                    f"      {lov} = ATOM(4,5)")
                                add = 2
                            elif k in (3, 4):
                                goals.append(
                                    f"      nlzf<{dv}> = 0")
                                goals.append(
                                    f"      se8f<{dv}> = 1")
                                goals.append(
                                    f"      {lov} "
                                    + ("!= " if k == 3 else "= ")
                                    + "ATOM(4,4)")
                                add = 2 if k == 3 else 3
                            else:
                                goals.append(
                                    f"      nlzf<{dv}> = 0")
                                goals.append(
                                    f"      se8f<{dv}> = 0")
                                goals.append(
                                    f"      {lov} "
                                    + ("!= " if k == 5 else "= ")
                                    + "ATOM(4,4)")
                                add = 5 if k == 5 else 6
                            dispvar = 0  # consumed by "disp" field
                        elif rm == "rip" or rm.startswith("rm"):
                            add = 1
                    elif f[0] == "disp":
                        add = 0
                    elif f[0] == "imm":
                        add = {"i8": 1, "i32": 4, "i64": 8}[f[1]]
                    elif f[0] == "rel":
                        add = 4
                    else:
                        raise ValueError(f)
                    if add:
                        av = g.v()
                        goals.append(
                            f"      nl_add<{acc}, {nl(add)}, "
                            f"ATOM(4,0)> = {av}")
                        acc = av
                goals.append(f"      n8 = {acc}")
                ovars = ", ".join(f"o{i}" for i in range(arity))
                fvars = ", ".join(f"v{i}" for i in range(1, g.n + 1))
                decls = ", ".join(x for x in (ovars, fvars) if x)
                out.append(f"  | fresh({decls}) {{")
                out.extend(goals)
                out.append("    }")
            earlier.extend(conds)
    out.append("}")
    return "\n".join(out)


ASSEMBLER = """
;; ---------- assembler ----------

;; pass1: label -> section-offset rows (nl8); insns advance pc by
;; enc2_len â€” label-independent by construction.
pass1 : <ops, pc8> <-> <labs> shape self where {
  | ops = [] { labs = [] }
  | fresh(o, n, rest, lb) {
      ops = PAIR(o, rest)   o = 'label(n)
      pass1<rest, pc8> = lb
      labs = PAIR(PAIR(n, pc8), lb)
    }
  | fresh(o, rest, n8, pc2, lb) {
      ops = PAIR(o, rest)   o = PAIR('op, _)
      enc2_len<o> = n8
      nl_add<pc8, n8, ATOM(4,0)> = pc2
      pass1<rest, pc2> = lb
      labs = lb
    }
}

assemble2 : <ops, labs, pc8> <-> <bytes> shape self where {
  | ops = [] { bytes = [] }
  | fresh(o, rest, rb) {
      ops = PAIR(o, rest)   o = 'label(_)
      assemble2<rest, labs, pc8> = rb
      bytes = rb
    }
  | fresh(o, rest, eb, n8, pc2, rb) {
      ops = PAIR(o, rest)   o = PAIR('op, _)
      enc2<o, labs, pc8> = eb
      enc2_len<o> = n8
      nl_add<pc8, n8, ATOM(4,0)> = pc2
      assemble2<rest, labs, pc2> = rb
      append<eb, rb> = bytes
    }
}

assemble : <ops> <-> <bytes> where {
  | fresh(labs) {
      pass1<ops, %s> = labs
      assemble2<ops, labs, %s> = bytes
    }
}
""" % (nl(0), nl(0))


def render() -> str:
    nib = "\n".join(
        f"  | n = ATOM(4,{n})  {{ p = ATOM(4,{(n - 1) & 15})   "
        f"w = ATOM(4,{1 if n == 0 else 0}) }}" for n in range(16))
    shl = "\n".join(f"  | h = ATOM(4,{h})  {{ v = {h * 16} }}"
                    for h in range(16))
    lon = "\n".join(f"  | n = ATOM(4,{n}) {{ ok = 1 }}"
                    for n in range(8))
    hin = "\n".join(f"  | n = ATOM(4,{n}) {{ ok = 1 }}"
                    for n in range(8, 16))
    lonf = "\n".join(f"  | n = ATOM(4,{n}) {{ f = {1 if n < 8 else 0} }}"
                     for n in range(16))
    hinf = "\n".join(f"  | n = ATOM(4,{n}) {{ f = {1 if n >= 8 else 0} }}"
                     for n in range(16))
    c48 = "\n".join(f"  | n = ATOM(4,{n}) {{ b = {n} }}"
                    for n in range(8))
    rflo = "\n".join(
        f"  | rf = ATOM(8,{r}) & lo = ATOM(8,{l}) {{ s = {r + l} }}"
        for r in range(0, 64, 8) for l in range(8))
    body = (NIBBLE
            .replace("%%NIBBLE_PRED%%", nib)
            .replace("%%NL0%%", nl(0))
            .replace("%%NL1%%", nl(1))
            .replace("%%SHL4%%", shl)
            .replace("%%LON4%%", lon)
            .replace("%%HIN4%%", hin)
            .replace("%%LON4F%%", lonf)
            .replace("%%HIN4F%%", hinf))
    regs = reg_tables().replace("%%C48%%", c48)
    fields = (FIELD_RELS
              .replace("%%RFLO%%", rflo)
              .replace("%%TRVA%%", nl(TRVA))
              .replace("%%NL4%%", nl(4)))
    return (HEADER + body + "\n" + regs + "\n" + fields + "\n"
            + symtab_rel() + "\n\n" + rex_rels() + "\n"
            + enc2_rels() + "\n\n" + enc2_len_rels() + "\n"
            + ASSEMBLER)


if __name__ == "__main__":
    sys.stdout.write(render())
