"""
target_fasmg — PE64 container as fasmg source text.

Same Target record shape and two-call contract as target_pe64 /
target_c: symbols() before assemble, pack() after.  pack() wraps the
isa_fasmg instruction stream into a complete fasmg unit — `format PE64
console`, .text/.data/.idata sections — whose manual import directory
mirrors target_pe64.build_idata's layout (descriptors, ILT, IAT with
`iat_<name>` slot labels, hint/name strings, dll name).

The emitted unit is a *witness artifact*: fasmg (x64.inc +
format/pe.inc) turns it into a runnable PE32+ exe — a third syntactic
realization of the same instruction data, verified behaviorally against
the byte-emitted kernel (compile() + run).

fasmg resolution is symbolic; `RVA label` handles section-relative
references inside .idata.  Include files come from fasmg's own
examples/x86/include — located via the ISAR_FASMG env var or the
default path next to this tree, and passed to fasmg through the
INCLUDE environment variable (fasmg's documented include search path).
"""
from __future__ import annotations

import os
import struct
import subprocess
import sys
import tempfile
from dataclasses import dataclass
from typing import Callable, Dict, List, Sequence, Tuple

_HOST = os.path.dirname(os.path.abspath(__file__))
if _HOST not in sys.path:
    sys.path.insert(0, _HOST)

from toolchain import NotRealized               # noqa: E402

DEFAULT_FASMG = os.path.normpath(os.path.join(
    _HOST, "..", "..", "isa-physics", "boostrap", "fasmg", "fasmg.exe"))
FASMG = os.environ.get("ISAR_FASMG", DEFAULT_FASMG)
FASMG_INC = os.path.join(os.path.dirname(FASMG), "examples", "x86",
                         "include")


def symbols(imports: Sequence[str],
            data_slots: Sequence[Tuple[str, int]]) -> Dict[str, str]:
    """Nominal symbol table — fasmg resolves iat_/data labels itself.
    Imports become `iat_<name>` labels on the IAT slots (the kernel's
    ("p", "iat_X") operands read through them)."""
    out = {s[0]: s[0] for s in data_slots}
    out.update({f"iat_{nm}": f"iat_{nm}" for nm in imports})
    return out


def pack(text: bytes, labels: Dict[str, int], imports: Sequence[str],
         data_slots: Sequence[Tuple[str, int]], R) -> bytes:
    """Pack assembled fasmg text into a complete PE64 source unit:
    format/header directives + .text (entry _start) + .data slots +
    manual .idata import directory mirroring target_pe64's layout.
    `labels` is kept for the caller's diagnostics."""
    del labels
    stack = getattr(R, "stack_reserve", 64 << 20) if R is not None \
        else 64 << 20
    lines: List[str] = [
        "; generated by target_fasmg — do not edit",
        "include 'format/format.inc'",
        "",
        # stack/heap/entry are standalone pe.inc directives, not
        # format-line settings; `at` ends the settings match, last
        f"format PE64 console at 0x140000000",
        "entry _start",
        f"stack {stack}",
        "",
        "section '.text' code readable executable",
        "",
    ]
    body = text.decode()
    lines.append(body.rstrip("\n"))
    lines += ["", "section '.data' data readable writeable", ""]
    for slot in data_slots:
        name, sz = slot[0], slot[1]
        init = slot[2] if len(slot) > 2 else b""
        if init:
            lines.append(f"  {name}: db "
                         + ",".join(f"0x{b:02x}" for b in init[:sz]))
            if len(init) < sz:
                lines.append(f"    rb {sz - len(init)}")
        else:
            lines.append(f"  {name}: rb {sz}")
    lines += ["", "section '.idata' import data readable writeable", ""]
    # canonical pe.inc import shape (examples/x86/win64.asm):
    # descriptor (OriginalFirstThunk=0, FirstThunk=iat) | zero
    # descriptor | IAT slots labelled iat_<name> | hint/names | dll
    lines += [
        "  dd 0,0,0,RVA kernel_name,RVA kernel_table",
        "  dd 0,0,0,0,0",
        "",
        "kernel_table:",
    ]
    for nm in imports:
        lines.append(f"  iat_{nm}: dq RVA h_{nm}")
    lines.append("  dq 0")
    for nm in imports:
        lines.append(f"h_{nm}: dw 0")
        lines.append(f"  db '{nm}',0")
    lines += ["kernel_name: db 'KERNEL32.DLL',0", ""]
    return ("\n".join(lines)).encode()


def compile(src: bytes, fasmg: str = FASMG) -> bytes:
    """fasmg.exe -> PE bytes.  INCLUDE carries fasmg's own include dir."""
    if not os.path.exists(fasmg):
        raise FileNotFoundError(
            f"fasmg missing: {fasmg} (set ISAR_FASMG)")
    inc = os.path.join(os.path.dirname(fasmg), "examples", "x86",
                       "include")
    env = dict(os.environ)
    env["INCLUDE"] = inc
    with tempfile.TemporaryDirectory() as td:
        asm = os.path.join(td, "kernel.asm")
        exe = os.path.join(td, "kernel.exe")
        with open(asm, "wb") as f:
            f.write(src)
        cp = subprocess.run([fasmg, asm, exe], capture_output=True,
                            text=True, env=env)
        if cp.returncode != 0 or not os.path.exists(exe):
            raise RuntimeError(
                f"fasmg failed rc={cp.returncode}: "
                f"{cp.stdout}{cp.stderr}")
        with open(exe, "rb") as f:
            return f.read()


@dataclass(frozen=True)
class Target:
    name: str         # "fasmg.pe64"
    os: str           # "windows"
    abi: str          # "win64"
    ext: str          # ".asm" — the artifact is source; compile() -> .exe
    pack: Callable    # pack(text, labels, imports, data_slots, R) -> bytes
    symbols: Callable  # symbols(imports, data_slots) -> {name: name}
    text_base: int    # 0 — nominal (fasmg resolves)


FASMG_PE64 = Target(
    name="fasmg.pe64",
    os="windows",
    abi="win64",
    ext=".asm",
    pack=pack,
    symbols=symbols,
    text_base=0,
)


def main() -> int:
    """Gate: emit the win64 token kernel as fasmg source, assemble it
    with fasmg.exe, run it on S K K I — the emitted program must be a
    working PE (behavioral equivalence with the byte-emitted kernel)."""
    import seed
    R = seed.Realization()
    src = seed.emit(R, tc=_tc())
    print(f"fasmg source: {len(src)}B")
    pe = compile(src)
    print(f"fasmg PE: {len(pe)}B  MZ={pe[:2] == b'MZ'}")
    ok = pe[:2] == b"MZ" and pe[0x40:0x44] == b"PE\x00\x00"
    print(f"{'OK' if ok else 'FAIL'} target_fasmg")
    return 0 if ok else 1


def _tc():
    import toolchain
    return toolchain.by_name("native.x86_64.fasmg")


if __name__ == "__main__":
    raise SystemExit(main())
