export const SYSTEMS = [
  // === COMBINATOR CALCULI ===
  {
    id: "iota",
    name: "Iota",
    symbol: "ι",
    family: "Combinator",
    carriers: { I: true, S: false, A: true, R: true },
    primitives: 1,
    turingComplete: true,
    symbolCount: null,
    description: "Single universal combinator. ιf = fSK. Minimal basis for all computation.",
    encoding: "ι",
    rewriteRules: ["ιf → fSK"],
    bisimQuotient: "SKI",
    color: "#4f98a3",
    notable: "Most compressed single-combinator universal basis",
    quotientClass: "TuringFunctional"
  },
  {
    id: "SKI",
    name: "SKI",
    symbol: "SKI",
    family: "Combinator",
    carriers: { I: true, S: true, A: true, R: true },
    primitives: 3,
    turingComplete: true,
    symbolCount: { S: 9, K: 7, I: 3 },
    description: "Three-combinator basis. S = substitution, K = constant, I = identity.",
    encoding: "S(K(SI))K",
    rewriteRules: ["Sfgx → fx(gx)", "Kxy → x", "Ix → x"],
    bisimQuotient: "λ-calculus",
    color: "#6daa45",
    notable: "Standard reference basis for combinatory logic",
    quotientClass: "TuringFunctional"
  },
  {
    id: "SK",
    name: "SK",
    symbol: "SK",
    family: "Combinator",
    carriers: { I: true, S: true, A: true, R: true },
    primitives: 2,
    turingComplete: true,
    symbolCount: { S: 9, K: 7 },
    description: "Two-combinator basis. I is derivable as SKK.",
    encoding: "SKK",
    rewriteRules: ["Sfgx → fx(gx)", "Kxy → x"],
    bisimQuotient: "λ-calculus",
    color: "#6daa45",
    notable: "I = SKK — identity emerges from constants",
    quotientClass: "TuringFunctional"
  },
  {
    id: "BCKW",
    name: "BCKW",
    symbol: "BCKW",
    family: "Combinator",
    carriers: { I: true, S: true, A: true, R: true },
    primitives: 4,
    turingComplete: true,
    symbolCount: { B: 35, C: 107, K: 7 },
    description: "B = composition, C = flip, K = constant, W = duplication. Linear logic friendly.",
    encoding: "B(BW)(BBC)",
    rewriteRules: ["Bfgx → f(gx)", "Cfxy → fyx", "Kxy → x", "Wfx → fxx"],
    bisimQuotient: "Linear λ-calculus",
    color: "#a86fdf",
    notable: "Corresponds to structural rules of sequent calculus",
    quotientClass: "Linear"
  },
  // === LAMBDA CALCULI ===
  {
    id: "untyped-lambda",
    name: "λ-calculus",
    symbol: "λ",
    family: "Lambda",
    carriers: { I: true, S: true, A: true, R: true },
    primitives: 3,
    turingComplete: true,
    symbolCount: null,
    description: "Variable, abstraction, application. Church's 1936 formalism. β-reduction as rewrite.",
    encoding: "λf.(λx.f(xx))(λx.f(xx))",
    rewriteRules: ["(λx.M)N → M[x:=N]"],
    bisimQuotient: "SKI",
    color: "#dd6974",
    notable: "Foundation of functional programming",
    quotientClass: "TuringFunctional"
  },
  {
    id: "lambda-typed",
    name: "Simply Typed λ",
    symbol: "λ→",
    family: "Lambda",
    carriers: { I: true, S: true, A: true, R: false },
    primitives: 4,
    turingComplete: false,
    symbolCount: null,
    description: "Untyped λ + type annotations. All terms normalize. No general recursion.",
    encoding: "λx:A.M",
    rewriteRules: ["(λx:A.M)N → M[x:=N]", "Type: (A→B)"],
    bisimQuotient: "Cartesian Closed Categories",
    color: "#dd6974",
    notable: "Curry-Howard correspondence: propositional logic proofs",
    quotientClass: "CCC"
  },
  {
    id: "system-f",
    name: "System F",
    symbol: "λ2",
    family: "Lambda",
    carriers: { I: true, S: true, A: true, R: false },
    primitives: 6,
    turingComplete: false,
    symbolCount: null,
    description: "Simply Typed λ + polymorphism (quantifying over types). Highly expressive.",
    encoding: "ΛX.λx:X.x",
    rewriteRules: ["(ΛX.M)[Y] → M[X:=Y]", "(λx:A.M)N → M[x:=N]"],
    bisimQuotient: "Reynolds parametricity",
    color: "#dd6974",
    notable: "Can represent all functions provably recursive in Peano Arithmetic",
    quotientClass: "CCC"
  },
  {
    id: "coc",
    name: "Calculus of Const.",
    symbol: "CoC",
    family: "Lambda",
    carriers: { I: true, S: true, A: true, R: false },
    primitives: 8,
    turingComplete: false,
    symbolCount: null,
    description: "Coquand & Huet 1986. Apex of Barendregt's cube. Dependent types (terms depend on types, types on terms).",
    encoding: "Πx:A.B",
    rewriteRules: ["β-reduction", "η-conversion", "dependent typecheck"],
    bisimQuotient: "Grothendieck universes",
    color: "#dd6974",
    notable: "Mathematical foundation for major modern proof assistants",
    quotientClass: "CCC"
  },
  {
    id: "coq",
    name: "Coq / Gallina",
    symbol: "Coq",
    family: "Lambda",
    carriers: { I: true, S: true, A: true, R: false },
    primitives: 10,
    turingComplete: false,
    symbolCount: null,
    description: "Interactive theorem prover based on the Calculus of Inductive Constructions (CIC). Compiles proof scripts into verified kernels.",
    encoding: "Inductive nat : Set := O | S : nat -> nat.",
    rewriteRules: ["β-reduction", "ι-reduction (inductive matches)", "δ-reduction (constants)"],
    bisimQuotient: "CIC Proof Theory",
    color: "#dd6974",
    notable: "Used to formally verify the Feit-Thompson odd order theorem and CompCert compiler",
    quotientClass: "CCC"
  },
  {
    id: "lean",
    name: "Lean Prover",
    symbol: "Lean",
    family: "Lambda",
    carriers: { I: true, S: true, A: true, R: false },
    primitives: 9,
    turingComplete: false,
    symbolCount: null,
    description: "Interactive theorem prover and programming language utilizing a dependent type theory kernel with quotient types and classical axioms.",
    encoding: "def add (n m : Nat) : Nat",
    rewriteRules: ["β-reduction", "Quotient reduction", "Inductive recursion"],
    bisimQuotient: "CIC with Quotients",
    color: "#dd6974",
    notable: "Rapidly becoming the standard for formalizing modern mathematics (e.g. Liquid Tensor Experiment)",
    quotientClass: "CCC"
  },
  // === REWRITING CALCULI ===
  {
    id: "term-rewriting",
    name: "Term Rewriting",
    symbol: "TRS",
    family: "Rewriting",
    carriers: { I: true, S: true, A: false, R: true },
    primitives: 4,
    turingComplete: true,
    symbolCount: null,
    description: "Abstract terms + algebraic rewrite rules. Computes via pattern matching.",
    encoding: "add(0,y) → y",
    rewriteRules: ["t(x1,..,xn) → s (pattern match)"],
    bisimQuotient: "Initial algebra",
    color: "#5591c7",
    notable: "Substrate of algebraic specification languages",
    quotientClass: "Rewriting"
  },
  {
    id: "string-rewriting",
    name: "String Rewriting",
    symbol: "SRS",
    family: "Rewriting",
    carriers: { I: true, S: false, A: false, R: true },
    primitives: 3,
    turingComplete: true,
    symbolCount: null,
    description: "Words over alphabet + string replacement rules. Semi-Thue systems.",
    encoding: "ab → ba",
    rewriteRules: ["u → v (substring replacement)"],
    bisimQuotient: "Monoid presentations",
    color: "#5591c7",
    notable: "Simplest Turing-complete rewriting — used in Post's theorem",
    quotientClass: "Rewriting"
  },
  // === PROCESS CALCULI ===
  {
    id: "pi-calculus",
    name: "π-calculus",
    symbol: "π",
    family: "Process",
    carriers: { I: true, S: true, A: true, R: true },
    primitives: 5,
    turingComplete: true,
    symbolCount: null,
    description: "Mobile processes communicating over channels. Names are first-class.",
    encoding: "x̄⟨y⟩.P | x(z).Q",
    rewriteRules: ["x̄⟨y⟩.P | x(z).Q → P | Q[z:=y]"],
    bisimQuotient: "Bisimilarity quotient (Milner)",
    color: "#d163a7",
    notable: "Basis of session types and distributed systems theory",
    quotientClass: "Process"
  },
  {
    id: "ccs",
    name: "CCS",
    symbol: "CCS",
    family: "Process",
    carriers: { I: true, S: true, A: true, R: true },
    primitives: 4,
    turingComplete: true,
    symbolCount: null,
    description: "Calculus of Communicating Systems. Milner 1980. Synchronous communication.",
    encoding: "a.P | ā.Q → P | Q",
    rewriteRules: ["a.P | ā.Q →τ P | Q"],
    bisimQuotient: "Strong bisimilarity",
    color: "#d163a7",
    notable: "First foundation for behavioral equivalence",
    quotientClass: "Process"
  },
  // === LOGIC / PROOF SYSTEMS ===
  {
    id: "prop-logic",
    name: "Prop. Logic",
    symbol: "PL",
    family: "Logic",
    carriers: { I: true, S: false, A: true, R: false },
    primitives: 4,
    turingComplete: false,
    symbolCount: null,
    description: "Boolean formulas + modus ponens. Decidable. NP-complete satisfiability.",
    encoding: "A → B, A ⊢ B",
    rewriteRules: ["Modus Ponens", "Resolution"],
    bisimQuotient: "Boolean algebra",
    color: "#437a22",
    notable: "Curry-Howard: simply typed λ-calculus",
    quotientClass: "CCC"
  },
  {
    id: "fol",
    name: "First-Order Logic",
    symbol: "FOL",
    family: "Logic",
    carriers: { I: true, S: true, A: true, R: true },
    primitives: 7,
    turingComplete: false,
    symbolCount: null,
    description: "Quantifiers over individuals. Semi-decidable. Gödel complete, arithmetic incomplete.",
    encoding: "∀x.∃y. P(x,y)",
    rewriteRules: ["∀-elim", "∃-intro", "Unification"],
    bisimQuotient: "Lindström's theorem",
    color: "#437a22",
    notable: "Gödel incompleteness — limits of formal provability",
    quotientClass: "ProofTheory"
  },
  {
    id: "linear-logic",
    name: "Linear Logic",
    symbol: "LL",
    family: "Logic",
    carriers: { I: true, S: true, A: true, R: true },
    primitives: 8,
    turingComplete: false,
    symbolCount: null,
    description: "Resources used exactly once. ! (bang) restores classical weakening/contraction.",
    encoding: "A ⊗ B, A ⅋ B, !A",
    rewriteRules: ["Cut elimination", "Resource management"],
    bisimQuotient: "∗-autonomous categories",
    color: "#437a22",
    notable: "Girard 1987 — corresponds to BCKW combinators",
    quotientClass: "Linear"
  },
  {
    id: "sequent-calculus",
    name: "Sequent Calculus",
    symbol: "LK/LJ",
    family: "Logic",
    carriers: { I: true, S: false, A: true, R: false },
    primitives: 12,
    turingComplete: false,
    symbolCount: null,
    description: "Gentzen's logical system representing proofs as trees of sequents. Separates structural rules (weakening, contraction, exchange) from logical rules.",
    encoding: "Γ ⊢ Δ",
    rewriteRules: ["Cut Elimination (Hauptsatz)", "Logical rules"],
    bisimQuotient: "Classical / Intuitionistic logic",
    color: "#437a22",
    notable: "Cut elimination theorem corresponds to normalization / execution",
    quotientClass: "ProofTheory"
  },
  {
    id: "isabelle-isar",
    name: "Isabelle/Isar",
    symbol: "Isar",
    family: "Logic",
    carriers: { I: true, S: true, A: true, R: true },
    primitives: 3,
    turingComplete: true,
    symbolCount: null,
    description: "Generic proof assistant based on Isabelle/Pure meta-logic with Isar structured proof language. Supports multiple object logics (HOL, ZF).",
    encoding: "theorem A: \"P ==> P\" by (rule assms)",
    rewriteRules: ["Resolution", "Rewriting (simp)", "Backchaining"],
    bisimQuotient: "LCF-style kernel / Higher-order logic",
    color: "#437a22",
    notable: "LCF kernel architecture ensures absolute proof correctness",
    quotientClass: "ProofTheory"
  },
  // === AUTOMATA ===
  {
    id: "turing-machine",
    name: "Turing Machine",
    symbol: "TM",
    family: "Automata",
    carriers: { I: true, S: true, A: false, R: true },
    primitives: 5,
    turingComplete: true,
    symbolCount: null,
    description: "Tape + head + state table. The universal reference for computability.",
    encoding: "δ(q,a) = (q',b,L/R)",
    rewriteRules: ["State transition + tape rewrite"],
    bisimQuotient: "Computable functions",
    color: "#006494",
    notable: "Church-Turing thesis — defines the boundary of computation",
    quotientClass: "Rewriting"
  },
  {
    id: "lambda-mu",
    name: "λμ-calculus",
    symbol: "λμ",
    family: "Lambda",
    carriers: { I: true, S: true, A: true, R: true },
    primitives: 5,
    turingComplete: true,
    symbolCount: null,
    description: "λ-calculus + control operators (call/cc). Parigot 1992. Classical logic proofs.",
    encoding: "μα.⟨α|M⟩",
    rewriteRules: ["(λx.M)N → M[x:=N]", "μα.⟨α|M⟩N → μα.⟨α|MN⟩"],
    bisimQuotient: "Classical sequent calculus",
    color: "#dd6974",
    notable: "Curry-Howard for classical logic — call/cc = excluded middle",
    quotientClass: "TuringFunctional"
  },
  // === BARKER IOTA ORBIT SPECIES ===
  {
    id: "barker-I",
    name: "Barker I",
    symbol: "I_ι",
    family: "Combinator",
    carriers: { I: true, S: false, A: false, R: false },
    primitives: 3,
    turingComplete: false,
    symbolCount: 3,
    description: "Identity carrier in Barker's iota orbit. I x = x. In the iota basis, it has a leaf size of 3 nodes: (ιι)ι.",
    encoding: "(ιι)ι",
    rewriteRules: ["I x → x"],
    bisimQuotient: "InvariantLayer",
    color: "#6daa45",
    notable: "Leaf size of 3 nodes in the iota tree basis",
    quotientClass: "Substrate"
  },
  {
    id: "barker-A",
    name: "Barker A",
    symbol: "A_ι",
    family: "Combinator",
    carriers: { I: true, S: false, A: true, R: false },
    primitives: 2,
    turingComplete: false,
    symbolCount: 11,
    description: "Adjacency / selection carrier in Barker's iota orbit. A x y = y. Ignores first arg, picks second. Expanded as (ι(ι(ιι)))(ιι).",
    encoding: "(ι(ι(ιι)))(ιι)",
    rewriteRules: ["A x y → y"],
    bisimQuotient: "Adjacency",
    color: "#6daa45",
    notable: "Leaf size of 11 nodes (6 leaves)",
    quotientClass: "Substrate"
  },
  {
    id: "barker-K",
    name: "Barker K",
    symbol: "K_ι",
    family: "Combinator",
    carriers: { I: true, S: false, A: false, R: true },
    primitives: 4,
    turingComplete: false,
    symbolCount: 7,
    description: "Rewrite / selection carrier in Barker's iota orbit. K x y = x. Ignores second arg, returns first. Expanded as ι(ι(ιι)).",
    encoding: "ι(ι(ιι))",
    rewriteRules: ["K x y → x"],
    bisimQuotient: "Rewrite",
    color: "#6daa45",
    notable: "Leaf size of 7 nodes (4 leaves)",
    quotientClass: "Substrate"
  },
  {
    id: "barker-S",
    name: "Barker S",
    symbol: "S_ι",
    family: "Combinator",
    carriers: { I: true, S: true, A: false, R: false },
    primitives: 5,
    turingComplete: false,
    symbolCount: 9,
    description: "State / distribution carrier in Barker's iota orbit. S f g x = f x (g x). Distributes shared argument. Expanded as ι(ι(ι(ιι))).",
    encoding: "ι(ι(ι(ιι)))",
    rewriteRules: ["S f g x → f x (g x)"],
    bisimQuotient: "State",
    color: "#6daa45",
    notable: "Leaf size of 9 nodes (5 leaves)",
    quotientClass: "Substrate"
  },
  {
    id: "barker-X",
    name: "Barker X",
    symbol: "X_ι",
    family: "Combinator",
    carriers: { I: true, S: true, A: true, R: true },
    primitives: 5,
    turingComplete: false,
    symbolCount: 11,
    description: "Self-application seed from which the four carriers are generated: X = S S K. Untypable under Hindley-Milner.",
    encoding: "ι(ι(ι(ι(ιι))))",
    rewriteRules: ["X X → K", "X (X X) → S"],
    bisimQuotient: "Closure",
    color: "#6daa45",
    notable: "Untypable carrier boundary. Infinite type: α ≅ α → β",
    quotientClass: "Substrate"
  },
  {
    id: "barker-Y",
    name: "Barker Y",
    symbol: "Y_ι",
    family: "Combinator",
    carriers: { I: true, S: true, A: true, R: true },
    primitives: 10,
    turingComplete: true,
    symbolCount: 35,
    description: "Fixed-point combinator in the self-application basis: Y = X(SB(CX)). Concrete instance of Theoretical Closure.",
    encoding: "X(S(S(KS)K)(S(S(BBS)(KK))X))",
    rewriteRules: ["Y f → f (Y f)"],
    bisimQuotient: "FixedPoint",
    color: "#6daa45",
    notable: "Concrete instance of Axiom 8: U(K) = K",
    quotientClass: "Substrate"
  },
  // === ISAR KERNEL ===
  {
    id: "ISAR",
    name: "ISAR Kernel",
    symbol: "I·R·A·S",
    family: "Substrate",
    carriers: { I: true, S: true, A: true, R: true },
    primitives: 4,
    turingComplete: true,
    symbolCount: null,
    description: "Invariant substrate. U(K) = I·R·A·S. Generates computational space itself. All other systems are Futamura projections within it.",
    encoding: "[[0,0,0,0],[0,0,0,0],[1,1,0,0],[0,0,0,0]]",
    rewriteRules: ["NORM = S·I", "APP = A·R", "COMP = R·A·S"],
    bisimQuotient: "Terminal object / Final coalgebra",
    color: "#4f98a3",
    notable: "Ontological ground — not a dialect but the substrate all dialects inhabit",
    quotientClass: "Substrate"
  }
];

export const edges = [
  ['untyped-lambda','SKI'],['SKI','iota'],['SK','SKI'],['BCKW','linear-logic'],['untyped-lambda','lambda-typed'],['lambda-typed','system-f'],['system-f','coc'],['pi-calculus','ccs'],['term-rewriting','string-rewriting'],['turing-machine','term-rewriting'],['ISAR','untyped-lambda'],['ISAR','pi-calculus'],['ISAR','term-rewriting'],['ISAR','fol'],['ISAR','SKI'],['untyped-lambda','lambda-mu'],['prop-logic','lambda-typed'],['fol','coc'],
  ['coc','coq'],['coc','lean'],['fol','isabelle-isar'],['sequent-calculus','linear-logic'],['isabelle-isar','sequent-calculus'],['ISAR','isabelle-isar'],
  ['iota','barker-I'],['barker-I','barker-A'],['barker-A','barker-K'],['barker-K','barker-S'],['barker-S','barker-X'],['barker-X','barker-I'],['barker-Y','barker-X'],['barker-Y','barker-S'],['ISAR','barker-Y']
];

export const familyColors = {
  Substrate: '#4f98a3',
  Combinator: '#6daa45',
  Lambda: '#dd6974',
  Rewriting: '#5591c7',
  Process: '#d163a7',
  Logic: '#437a22',
  Automata: '#006494'
};

export const QUOTIENT_CLASSES = {
  "Substrate": {
    name: "Operational Substrate",
    color: "#4f98a3",
    description: "The ontological ground and final coalgebra. The invariant foundation through which all other formalisms are decoded as semantic views."
  },
  "TuringFunctional": {
    name: "Turing-Complete Functional",
    color: "#dd6974",
    description: "Turing-complete deterministic functional calculi with general recursion (λ-calculus, SKI, Iota, λμ)."
  },
  "CCC": {
    name: "Cartesian Closed Structure",
    color: "#dd6974",
    description: "Decidable type systems and logics matching Cartesian Closed Categories and standard Curry-Howard (Simply Typed λ, System F, CoC, Coq, Lean, Prop Logic)."
  },
  "Process": {
    name: "Process Calculi",
    color: "#d163a7",
    description: "Systems for concurrent communication, mobility, and interactive execution (CCS, π-calculus)."
  },
  "Rewriting": {
    name: "Rewriting & State",
    color: "#5591c7",
    description: "State machines and term/string replacement rules. Computes via step-by-step syntactic transformation rather than abstraction (Turing Machine, TRS, SRS)."
  },
  "Linear": {
    name: "Resource Logics & Structural Rules",
    color: "#a86fdf",
    description: "Logics and combinators with controlled duplication and discarding of resources (linear logic, BCKW)."
  },
  "ProofTheory": {
    name: "Proof Theory & Meta-Logics",
    color: "#437a22",
    description: "First-Order Logic, Gentzen's Sequent Calculus, and LCF-style proof assistants mapping higher-order structural proof terms."
  }
};

export const COMB_EXPANSIONS = {
  'ι': 'ι',
  'I': '(ιι)',
  'K': '(ι(ι(ιι)))',
  'S': '(ι(ι(ι(ιι))))',
  'B': 'S(KS)K',
  'C': 'S(BBS)(KK)',
  'A': 'KI',
  'U': 'CI',
  'Z': 'BK',
  'P': 'BC(CI)',
  'R': 'CC',
  'O': 'B(BK)(BC(CI))',
  'J': 'BK(CI)',
  'S\'': 'B(BS)B',
  'B\'': 'BB',
  'C\'': 'B(BC)B',
  'C\'B': '(C\'B)',
  'K2': 'BKK',
  'K3': 'BK2K',
  'K4': 'BK3K',
  'X': 'ιS',
  'Y': 'X(S B (C X))'
};
